# Generated by Django 4.1.1 on 2023-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_publish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of publishing'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
    ]
